# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cfae1c8e37cef47f4937ab3043262ce764a6dfe458052defc8b261268722d1042e7655d07c70728accfe1aab4f497a4308a6c1a0ed79246ba8a34da3d584d37

test:
  secret_key_base: 52715f893adceb984b863f02c1c06aa1cbed8495beb8a6199421c39d698915b6655b27bab8bb2f6df103306a0368a611f521c8d7378fecebdf0b0bbaa0a5f6ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
